### ISSUE TITLE
Mscoco file needed

### ISSUE THREAD

**Issue by vinevix** [lezhang-thu/xtransformer-ppo#1]
Hi, I'm trying to pretrain my model with your code but some mscoco files are needed: where can I find them? File on https://cocodataset.org/#download don't have stuff like 

'TARGET_SEQ_PATH': './mscoco/sent/coco_train_target.pkl',
                 'TEST_ATT_FEATS': './mscoco/feature/up_down_10_100',
                 'TEST_GV_FEAT': '',
                 'TEST_ID': './mscoco/txt/coco_test_image_id.txt',
                 'TRAIN_ATT_FEATS': './mscoco/feature/up_down_10_100',
                 'TRAIN_GV_FEAT': '',
                 'TRAIN_ID': './mscoco/txt/coco_train_image_id.txt',
                 'VAL_ATT_FEATS': './mscoco/feature/up_down_10_100',
                 'VAL_GV_FEAT': '',
                 'VAL_ID': './mscoco/txt/coco_val_image_id.txt'},

**Comment by lezhang-thu** [comment]
Plz prepare the training data as in
https://github.com/JDAI-CV/image-captioning#data-preparation
Thanks.
